name: Update vcpkg Versions

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

    paths:
      - "ports/**/vcpkg.json"

permissions:
  contents: write # required to push commit to PR branch

jobs:
  update-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clone and bootstrap vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git
          ./vcpkg/bootstrap-vcpkg.sh

      - name: Run x-add-version for all ports
        run: |
          ./vcpkg/vcpkg \
            --x-builtin-ports-root=./ports \
            --x-builtin-registry-versions-dir=./versions \
            x-add-version --all --verbose

      - name: Commit updated versions files
        run: |
          if ! git diff --quiet; then
            echo "Committing updated versions..."

            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

            git add versions
            git commit -m "chore: update vcpkg versions files"
            git push
          else
            echo "No version updates needed."
          fi
